Repository whamcloud/device-scanner, pull requests merged in 2018-03, with the labels that each got.

#97 - Bump Fable.Powerpack
  paket-files/paket.restore.cached
  paket.lock
Labels: enhancement

#98 bump deps
  paket-files/paket.restore.cached
  paket.lock
Labels: enhancement

#80 Update command state
  IML.IntegrationTest/IntegrationTest.fs
  IML.IntegrationTest/__snapshots__/IntegrationTest.fs.snap
  IML.IntegrationTestFramework/source/IntegrationTestFramework.fs
  IML.IntegrationTestFramework/test/IntegrationTest.fs
  package.json
Labels: enhancement

#100 Alter triggerin scriptlet for ZFS
  device-scanner.spec
Labels: bug, enhancement

#105 bump + some small cleanups
  .travis.yml
  IML.IntegrationTestFramework/source/IntegrationTestFramework.fs
  IML.Listeners/UdevListener/Main.fs
  package-lock.json
  package.json
  paket-files/paket.restore.cached
  paket.lock
Labels: enhancement

#106 Replace explicit timers with use of setInterval
  IML.ScannerProxyDaemon/src/Heartbeat.fs
  IML.ScannerProxyDaemon/src/IML.ScannerProxyDaemon.fsproj
  IML.ScannerProxyDaemon/src/Main.fs
Labels: enhancement

#104 Create 9 disks to be used for integration testing
  IML.IntegrationTest/__snapshots__/IntegrationTest.fs.snap
  Vagrantfile
Labels: enhancement

#108 Udev remove not matching expectation
  IML.DeviceScannerDaemon/src/Udev.fs
  device-scanner.spec
Labels: bug

#110 Use buffer serializer in integration tests
  IML.IntegrationTest/IntegrationTest.fs
  IML.IntegrationTest/__snapshots__/IntegrationTest.fs.snap
  IML.IntegrationTest/jest.config.js
  Vagrantfile
  paket-files/paket.restore.cached
  paket.lock
Labels: enhancement

#113 Switch to whitelist
  .npmignore
  mock-build.sh
  package-lock.json
  package.json
Labels: bug, enhancement

#117 Integrate eslint
  .eslintrc
  buffer-serializer.js
  package-lock.json
  package.json
  rollup-config.js
Labels: enhancement

#123 Bump deps + refactor test commands
  .travis.yml
  IML.DeviceScannerDaemon/src/paket.references
  IML.DeviceScannerDaemon/test/paket.references
  README.md
  package-lock.json
  package.json
  paket-files/paket.restore.cached
  paket.lock
Labels: enhancement

#126 Pin docker version till next release of rust-libzfs.
  .travis.yml
Labels: bug

#124 Add fn to convert hex to string
  IML.CommonLibrary/jest.config.js
  IML.CommonLibrary/src/IML.CommonLibrary.fsproj
  IML.CommonLibrary/src/Main.fs
  IML.CommonLibrary/src/paket.references
  IML.CommonLibrary/test/IML.CommonLibraryTest.fsproj
  IML.CommonLibrary/test/MainTest.fs
  IML.CommonLibrary/test/paket.references
  IML.DeviceScannerDaemon/src/IML.DeviceScannerDaemon.fsproj
  IML.DeviceScannerDaemon/src/Udev.fs
  IML.DeviceScannerDaemon/src/Zed.fs
  device-scanner.sln
  package.json
Labels: enhancement
