Repository whamcloud/device-scanner, pull requests merged in 2019-05, with the labels that each got.

#256 Update deps
  .copr/Makefile
  .gitignore
  .travis.yml
  Cargo.lock
  device-aggregator/src/main.rs
  device-scanner-daemon/src/main.rs
  device-scanner-daemon/src/reducers/udev.rs
  device-scanner-daemon/src/state.rs
  device-scanner-proxy/src/main.rs
  device-types/src/lib.rs
  iml-device-scanner.spec
  mount-emitter/src/lib.rs
  uevent-listener/src/main.rs
  zed-enhancer/src/lib.rs
Labels: enhancement

#257 Some general Fixups
  Cargo.lock
  device-scanner-daemon/systemd-units/device-scanner.target
  device-scanner-proxy/Cargo.toml
  device-scanner-proxy/src/main.rs
  device-scanner-proxy/systemd-units/scanner-proxy.service
  device-types/Cargo.toml
  iml-device-scanner.spec
  mount-emitter/Cargo.toml
  mount-emitter/src/bin/mount_emitter.rs
  mount-emitter/src/lib.rs
  zed-enhancer/Cargo.toml
  zed-enhancer/src/lib.rs
  zed-enhancer/src/main.rs
  zed-enhancer/systemd-units/zed-enhancer.service
  zed-enhancer/systemd-units/zed-enhancer.socket
Labels: tech debt

#258 Send mount
  Cargo.lock
  device-scanner-daemon/src/state.rs
  device-types/Cargo.toml
  device-types/src/lib.rs
  uevent-listener/Cargo.toml
  uevent-listener/src/main.rs
Labels: enhancement

#259 Use OrdSet instead of HashSet
  device-scanner-daemon/src/reducers/udev.rs
  device-scanner-daemon/src/reducers/zed.rs
  device-scanner-daemon/src/state.rs
  device-types/src/lib.rs
  uevent-listener/src/main.rs
Labels: enhancement

#254 Copr 5.0
  .copr/Makefile
  .dockerignore
  .gitignore
  .paket/Paket.Restore.targets
  .travis.yml
  Vagrantfile
  build.fsx
  build.fsx.lock
  iml-device-scanner.spec
Labels: enhancement

#262 Update device-aggregator socket
  IML.DeviceAggregatorDaemon/systemd-units/device-aggregator.socket
Labels: bug

#264 Bump to 2.2.1
  iml-device-scanner.spec
  package-lock.json
  package.json
Labels: enhancement

#263 Add device path ordering
  Cargo.lock
  device-scanner-daemon/Cargo.toml
  device-scanner-daemon/src/connections.rs
  device-scanner-daemon/src/reducers/mount.rs
  device-scanner-daemon/src/reducers/snapshots/tests__reducers::mount::tests::test_mount_update.snap
  device-scanner-daemon/src/reducers/udev.rs
  device-scanner-daemon/src/reducers/zed.rs
  device-scanner-daemon/src/state.rs
  device-types/Cargo.toml
  device-types/src/lib.rs
  device-types/src/snapshots/tests__tests::test_device_path_ordering.snap
  device-types/src/udev.rs
  device-types/src/uevent.rs
  mount-emitter/src/lib.rs
  mount-emitter/src/snapshots/tests__tests::test_list_mount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_mount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_move.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_remount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_umount.snap
  mount-emitter/src/snapshots/tests__tests::test_swap.snap
  mount-emitter/src/snapshots/tests__tests::test_swap_extra.snap
  uevent-listener/src/main.rs
Labels: enhancement

#269 Ensure zpool is returned after being taken
  .travis.yml
  device-scanner-daemon/src/reducers/zed.rs
  zed-enhancer/systemd-units/zed-enhancer.service
  zed-enhancer/systemd-units/zed-enhancer.socket
Labels: bug

#267 Add interop with existing linux plugin
  .travis.yml
  Cargo.lock
  device-aggregator/Cargo.toml
  device-aggregator/src/aggregator_error.rs
  device-aggregator/src/cache.rs
  device-aggregator/src/lib.rs
  device-aggregator/src/linux_plugin_transforms.rs
  device-aggregator/src/main.rs
  device-aggregator/src/snapshots/tests__linux_plugin_transforms::tests::test_devtree2linuxoutput.snap
  device-aggregator/src/snapshots/tests__linux_plugin_transforms::tests::test_devtree2linuxoutput_dataset.snap
  device-aggregator/src/snapshots/tests__linux_plugin_transforms::tests::test_devtree2linuxoutput_zpool.snap
  device-aggregator/systemd-units/device-aggregator.service
  device-scanner-daemon/src/state.rs
  device-scanner-daemon/systemd-units/device-scanner.target
  device-types/src/devices.rs
  iml-device-scanner.spec
Labels: enhancement

#273 Add mounts to ZPool and Dataset structs
  device-scanner-daemon/src/state.rs
  device-types/src/devices.rs
  device-types/src/lib.rs
Labels: enhancement

#274 Add fs_label and fs_uuid
  device-scanner-daemon/src/reducers/udev.rs
  device-scanner-daemon/src/state.rs
  device-types/src/devices.rs
  device-types/src/lib.rs
  device-types/src/uevent.rs
  uevent-listener/src/main.rs
Labels: enhancement

#275 Add panic_handler to tokio usage
  Cargo.lock
  device-scanner-daemon/src/main.rs
  device-scanner-proxy/src/main.rs
  zed-enhancer/src/main.rs
Labels: bug

#276 Account for vd devices
  device-aggregator/src/linux_plugin_transforms.rs
  device-scanner-daemon/src/state.rs
  device-types/src/devices.rs
Labels: bug

#277 Add GetMounts cmd
  device-scanner-daemon/src/connections.rs
  device-scanner-daemon/src/main.rs
  device-scanner-daemon/src/state.rs
  device-types/src/lib.rs
Labels: enhancement

#278 Use mutable reference for pool changes
  device-scanner-daemon/src/reducers/zed.rs
  device-scanner-daemon/systemd-units/device-scanner.service
  device-scanner-proxy/systemd-units/scanner-proxy.service
Labels: tech debt

#279 Filter out `tmp/mntXXXXXX` from device-aggregator output
  .travis.yml
  Cargo.lock
  device-aggregator/src/linux_plugin_transforms.rs
  device-scanner-daemon/src/reducers/snapshots/tests__reducers::mount::tests::test_mount_update.snap
  device-types/src/snapshots/tests__tests::test_device_path_ordering.snap
  mount-emitter/src/snapshots/tests__tests::test_line_to_hashmap_mount.snap
  mount-emitter/src/snapshots/tests__tests::test_line_to_hashmap_swap.snap
  mount-emitter/src/snapshots/tests__tests::test_list_mount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_mount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_move.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_remount.snap
  mount-emitter/src/snapshots/tests__tests::test_poll_umount.snap
  mount-emitter/src/snapshots/tests__tests::test_swap.snap
  mount-emitter/src/snapshots/tests__tests::test_swap_extra.snap
Labels: bug

#280 Use single-threaded runtime for zed-enhancer daemon
  Cargo.lock
  device-scanner-daemon/src/main.rs
  zed-enhancer/src/lib.rs
  zed-enhancer/src/main.rs
Labels: bug
